// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0Ip9N5KLy9qQIqj3DjXgSogmSyOGeriA',
    appId: '1:1063124337540:web:01916206d1025a6360d3d1',
    messagingSenderId: '1063124337540',
    projectId: 'forourdisaster',
    authDomain: 'forourdisaster.firebaseapp.com',
    storageBucket: 'forourdisaster.firebasestorage.app',
    measurementId: 'G-JFEYDVKYM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe5ibi_2oZGtQQTJ4skwCZA4cpYEL4WAE',
    appId: '1:1063124337540:android:06c2fcc1d8bd815760d3d1',
    messagingSenderId: '1063124337540',
    projectId: 'forourdisaster',
    storageBucket: 'forourdisaster.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7s1gSozHCUXeT7U5tYHEbX4AZTZYdCrc',
    appId: '1:1063124337540:ios:e559dd765d8b945660d3d1',
    messagingSenderId: '1063124337540',
    projectId: 'forourdisaster',
    storageBucket: 'forourdisaster.firebasestorage.app',
    iosBundleId: 'com.example.formydisaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7s1gSozHCUXeT7U5tYHEbX4AZTZYdCrc',
    appId: '1:1063124337540:ios:e559dd765d8b945660d3d1',
    messagingSenderId: '1063124337540',
    projectId: 'forourdisaster',
    storageBucket: 'forourdisaster.firebasestorage.app',
    iosBundleId: 'com.example.formydisaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0Ip9N5KLy9qQIqj3DjXgSogmSyOGeriA',
    appId: '1:1063124337540:web:30abdec8c551b63760d3d1',
    messagingSenderId: '1063124337540',
    projectId: 'forourdisaster',
    authDomain: 'forourdisaster.firebaseapp.com',
    storageBucket: 'forourdisaster.firebasestorage.app',
    measurementId: 'G-J0RB2K2NY0',
  );
}
